// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css'; // 👈 1. Импорт стилей кошелька
import { Providers } from "./providers";     // 👈 2. Импорт нашей обертки
import { ConnectButton } from "@rainbow-me/rainbowkit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web3 App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header style={{ position: 'fixed', top: 0, left: 0, right: 0, height: '60px', background: '#fff', borderBottom: '1px solid #eee', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 1.5rem', zIndex: 1000 }}>
            <h1 style={{ fontSize: '1.2rem', fontWeight: 'bold' }}>Web3 App</h1>
            <ConnectButton />
          </header>
          <main style={{ paddingTop: '60px' }}>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}